-- AlterTable
ALTER TABLE "flights" ALTER COLUMN "departure_airport" DROP NOT NULL,
ALTER COLUMN "arrival_airport" DROP NOT NULL,
ALTER COLUMN "departure_terminal_name" DROP NOT NULL,
ALTER COLUMN "arrival_terminal_name" DROP NOT NULL,
ALTER COLUMN "flight_number" DROP NOT NULL,
ALTER COLUMN "airline_code" DROP NOT NULL,
ALTER COLUMN "airplane_code" DROP NOT NULL,
ALTER COLUMN "free_baggage" DROP NOT NULL,
ALTER COLUMN "cabin_baggage" DROP NOT NULL,
ALTER COLUMN "departure_time" DROP NOT NULL,
ALTER COLUMN "arrival_time" DROP NOT NULL,
ALTER COLUMN "duration_minute" DROP NOT NULL,
ALTER COLUMN "class" DROP NOT NULL,
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "arrival_date" DROP NOT NULL,
ALTER COLUMN "arrival_timestamp" DROP NOT NULL,
ALTER COLUMN "departure_date" DROP NOT NULL,
ALTER COLUMN "departure_timestamp" DROP NOT NULL;
